configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dds-dhanendra73984-8c8ho1%2Fapi-rate-limiter-sdk-dds-8752cd8864ff6e09352d2463f32a25e440dfc553e835ab9e2c76588b398e7b00.yml
